set define off;


----------------ObjectDeleteScript----------------

delete  from maxobjectcfg  where objectname='IMGLIBUSER';
delete  from maxtablecfg  where TABLENAME='IMGLIBUSER';
delete  from maxattributecfg  where OBJECTNAME='IMGLIBUSER';
delete  from maxsysindexes where TBNAME= 'IMGLIBUSER';
delete from maxsyskeys where IXNAME='IMGLIBUSER_NDX1';
delete  from maxrelationship where PARENT= 'IMGLIBUSER';
delete  from maxsequence where TBNAME= 'IMGLIBUSER';


----------------ObjectInsertScript----------------



----------------CreateObjectScript----------------

insert into maxobjectcfg ( OBJECTNAME, CLASSNAME, DESCRIPTION, EAUDITENABLED, EAUDITFILTER, ENTITYNAME, ESIGFILTER, EXTENDSOBJECT, IMPORTED, ISVIEW, PERSISTENT, SERVICENAME, SITEORGTYPE, USERDEFINED, CHANGED, MAINOBJECT, INTERNAL, MAXOBJECTID, TEXTDIRECTION) values ( 'IMGLIBUSER', 'psdi.mbo.custapp.CustomMboSet', '用户定义图像表', 0, null, 'IMGLIBUSER', null, null, 0, 0, 1, 'CUSTAPP', '系统', 1,'I', 0, 0, MAXOBJECTCFGSEQ.nextval, null);


----------------CreateTableScript----------------

insert into maxtablecfg ( TABLENAME, ADDROWSTAMP, EAUDITTBNAME, ISAUDITTABLE, RESTOREDATA, STORAGEPARTITION, TEXTSEARCHENABLED, LANGTABLENAME, LANGCOLUMNNAME, UNIQUECOLUMNNAME, ISLANGTABLE, MAXTABLEID, ALTIXNAME, TRIGROOT, CONTENTATTRIBUTE, STORAGETYPE, EXTTABLENAME) values ( 'IMGLIBUSER', 1, null, 0, 0, 'MAXDATA', 0, null, null, 'IMGLIBUSERID', 0, MAXTABLECFGSEQ.nextval, null, 'IMGLIBUSER', null, 0, null);


----------------CreateAttributeScript----------------

insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'IMGLIBUSERID', 'IMGLIBUSERID', null, 1, 0, null, 'IMGLIBUSERID', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 19, 'BIGINT', 1, 1, 1, 1, '唯一标识', null, null, 0, '唯一标识', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'IMAGE', 'IMAGE', null, 2, 0, null, 'IMAGE', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 999999, 'BLOB', 0, 1, 1, null, '图像文件 CLOB 字段', null, null, 0, '图像文件 CLOB 字段', 1,'I', 'NONE', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'IMAGENAME', 'IMAGENAME', null, 3, 0, null, 'IMAGENAME', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 100, 'ALN', 0, 0, 1, null, '图像文件的文件名或描述', null, null, 0, '图像文件的文件名或描述', 1,'I', 'NONE', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'MIMETYPE', 'MIMETYPE', null, 4, 0, null, 'MIMETYPE', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 50, 'ALN', 0, 1, 1, null, '图象的内容/MIME 类型', null, null, 0, '图象的内容/MIME 类型', 1,'I', 'NONE', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 1, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'SN', 'SN', null, 5, 0, null, 'SN', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 12, 'INTEGER', 0, 0, 1, null, '序号', null, null, 0, '序号', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'REFOBJECT', 'REFOBJECT', null, 6, 0, null, 'REFOBJECT', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 30, 'UPPER', 1, 1, 1, null, '参考对象', 'OBJECTNAME', 'MAXOBJECT', 0, '参考对象', 1,'I', 'WILDCARD', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);
insert into maxattributecfg ( OBJECTNAME, ATTRIBUTENAME, ALIAS, AUTOKEYNAME, ATTRIBUTENO, CANAUTONUM, CLASSNAME, COLUMNNAME, DEFAULTVALUE, DOMAINID, EAUDITENABLED, ENTITYNAME, ESIGENABLED, ISLDOWNER, ISPOSITIVE, LENGTH, MAXTYPE, MUSTBE, REQUIRED, PERSISTENT, PRIMARYKEYCOLSEQ, REMARKS, SAMEASATTRIBUTE, SAMEASOBJECT, SCALE, TITLE, USERDEFINED, CHANGED, SEARCHTYPE, MLSUPPORTED, MLINUSE, HANDLECOLUMNNAME, MAXATTRIBUTEID, RESTRICTED, LOCALIZABLE, TEXTDIRECTION, COMPLEXEXPRESSION, EXTENDED) values ( 'IMGLIBUSER', 'REFOBJECTID', 'REFOBJECTID', null, 7, 0, null, 'REFOBJECTID', null, null, 0, 'IMGLIBUSER', 0, 0, 0, 19, 'BIGINT', 0, 0, 1, null, '参考对象唯一标识', null, null, 0, '参考对象唯一标识', 1,'I', 'EXACT', 0, 0, null, MAXATTRIBUTECFGSEQ.nextval, 0, 0, null, null, 0);


----------------CreateindexScript----------------

insert into maxsysindexes ( NAME, TBNAME, UNIQUERULE, CHANGED, CLUSTERRULE, STORAGEPARTITION, REQUIRED, TEXTSEARCH, MAXSYSINDEXESID) values ( 'IMGLIBUSER_NDX1', 'IMGLIBUSER', 'U','Y', 0, 'MAXDATA', 1, 0, MAXSYSINDEXESSEQ.nextval);


----------------CreateKeyScript----------------

insert into maxsyskeys ( IXNAME, COLNAME, COLSEQ, ORDERING, CHANGED, MAXSYSKEYSID) values ( 'IMGLIBUSER_NDX1', 'IMGLIBUSERID', 1, 'A','Y', MAXSYSKEYSSEQ.nextval);


----------------CreateRelationScript----------------



----------------CreateSequenceScript----------------

insert into maxsequence ( TBNAME, NAME, MAXRESERVED, MAXVALUE, RANGE, SEQUENCENAME, MAXSEQUENCEID) values ( 'IMGLIBUSER', 'IMGLIBUSERID', 1, null, null, 'IMGLIBUSERIDSEQ', MAXSEQUENCESEQ.nextval);


----------------Update Maximo Sequence----------------

update maxsequence set maxreserved=(select max(IMGLIBUSERID)+1 from IMGLIBUSER) where tbname='IMGLIBUSER' and name='IMGLIBUSERID';


----------------CreateAutokeyScript----------------

commit;

